id: A8875F7EF
base_file: f8504.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:49:29.560537
  last_modified_at: 2022-06-17 12:49:29.560540
