id: A8875F7EF
base_file: fAC48.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:49:29.570329
  last_modified_at: 2022-06-17 12:49:29.570332
