id: A8875F7EF
base_file: fA5E7.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:49:29.567522
  last_modified_at: 2022-06-17 12:49:29.567525
